European Vanilla Call and Put Options: std_norm Namespace Reference
std_norm Namespace Reference
Functions
double pdf (double x)
Probability density function (PDF) for \(\mathcal{N}(0, 1) \):
double cdf (double x)
Cumulative distribution function (CDF) for \(\mathcal{N}(0, 1) \):
Variables
const auto norm_coeff = 1.0 / std::pow(2.0 * M_PI, 0.5)
Function Documentation
cdf()
double std_norm::cdf (double x)
Cumulative distribution function (CDF) for \(\mathcal{N}(0, 1) \):
\(\displaystyle \Phi(x) = \frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{x} e^{-t^2 / 2} dt \).
The definite integral calculation is adapted from Michael Halls-Moore. C++ for Quantitative Finance, 2010 which in turn is an adaptation from M. S. Joshi. C++ Design Patterns and Derivatives Pricing, 2nd Ed. Cambridge University Press, 2008.
Parameters
x
Returns
double
References pdf().
Referenced by EuropeanVanillaOption::callPrice(), and EuropeanVanillaOption::putPrice().
pdf()
double std_norm::pdf (double x)
Probability density function (PDF) for \(\mathcal{N}(0, 1) \):
\(\displaystyle f(x) = \frac{1}{\sqrt{2 \pi}} e^{-x^2 / 2} \).
Parameters
x
Returns
double
References norm_coeff.
Referenced by cdf().
Variable Documentation
norm_coeff
const auto std_norm::norm_coeff = 1.0 / std::pow(2.0 * M_PI, 0.5)
Referenced by pdf().